version: '3.8'

services:
  db:
    image: postgres:12.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: thws
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  app:
    image: quarkus/students-jvm
    environment:
      quarkus.datasource.jdbc.url: jdbc:postgresql://db:5432/thws
      thws.location: "within the cloud"
    ports:
      - "9090:8080"